/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BiliBili: typeof import('./../components/BiliBili.vue')['default']
    Box: typeof import('./../components/Box.vue')['default']
    Hello: typeof import('./../components/Hello.vue')['default']
    ResponsiveBox: typeof import('./../components/ResponsiveBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
